debug

diff --git a/.github/workflows/lab4.yaml b/.github/workflows/lab4.yaml
--- a/.github/workflows/lab4.yaml
+++ b/.github/workflows/lab4.yaml
@@ -54,12 +54,15 @@ jobs:
         uses: actions/cache@v4
         with:
           path: ~/.npm 
-          key: node-modules-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
+          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
           restore-keys: |
             node-modules-${{ runner.os }}-
 
       - name: Debug package-lock.json
-        run: ls -l **/package-lock.json || echo "package-lock.json not found"
+        run: ls -l package-lock.json || echo "package-lock.json not found"
+
+      - name: Debug2 package-lock.json
+        run: ls -l my-node-app/package-lock.json || echo "package-lock.json not found"  
                     
       - name: Install dependencies
         run: npm install
